---
title: "Quadvariate Viz"
---

Use this file to generate a professional looking **quadvariate** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.

```{r}
library(tidyverse)
library(ggthemes)

messy_aussie_data <- read_csv("../data/ABS,ABS_REGIONAL_ASGS2021,1.3.0+CABEE_5+CABEE_15+CABEE_10+MIGRATION_7+MIGRATION_4+BD_3+BD_4+BD_2+ERP_P_20.SA3..A.csv")

aussie_data <- messy_aussie_data |>
  select(Region, `Data Item`, OBS_VALUE) |>
  mutate(`Data Item` = fct_recode(`Data Item`,
                                  "fert_rate" = "Total fertility rate (births per female) (rate)",
                                  "net_over_migr" = "Net overseas migration (no.)",
                                  "net_inter_migr" = "Net internal migration (no.)",
                                  "reg_births" = "Registered births (no.)",
                                  "reg_deaths" = "Registered deaths (no.)",
                                  "total_pop" = "Estimated resident population: Persons (no.)",
                                  "total_busi_exits" = "Total business exits (no.)",
                                  "total_busi_entr" = "Total business entries (no.)",
                                  "total_busi" = "Total businesses (no.)")) |>
  pivot_wider(names_from = `Data Item`, values_from = OBS_VALUE) |>
  filter(!is.na(fert_rate)) |>
  mutate(net_pop = reg_births - reg_deaths) |> # total births - deaths
  mutate(net_migr = net_over_migr + net_inter_migr) |> # the total change in migrants
  mutate(net_busi = total_busi_entr - total_busi_exits) |> # the total change in businesses
  mutate(pct_inter_migr = (net_inter_migr / total_pop) * 100) |> # net internal migration as a percent of total pop
  mutate(pct_over_migr = (net_over_migr / total_pop) * 100) |> # net overseas migration as a percent of total pop
  mutate(pct_migr = (net_migr / total_pop) * 100) |> # the pct change in population by migrants
  mutate(pct_pop = (net_pop / total_pop) * 100) |> # the pct change in population
  mutate(pct_busi = (net_busi / total_busi) * 100) |> # the pct change in businesses
  mutate(yn_fert_rate = cut(fert_rate,
                          breaks = c(0, 2.1, Inf),
                          labels = c("Below replacement rate", "Above replacement rate"),
                          include.lowest = TRUE)) |>
  mutate(yn_net_migr = cut(net_migr,
                          breaks = c(-99999999, 0, Inf),
                          labels = c("Lost population through migration", "Gained population through migration"),
                          include.lowest = TRUE)) |>
  mutate(yn_inter_migr = cut(net_inter_migr,
                          breaks = c(-99999999, 0, Inf),
                          labels = c("Net Negative internal migration", "Net Positive internal migration"),
                          include.lowest = TRUE)) |>
  mutate(yn_over_migr = cut(net_over_migr,
                          breaks = c(-99999999, 0, Inf),
                          labels = c("Lost population through overseas migration", "Gained population through overseas migration"),
                          include.lowest = TRUE)) |>
  mutate(yn_net_busi = cut(net_busi,
                          breaks = c(-99999999, 0, Inf),
                          labels = c("Lost more businesses than gained", "Gained more businesses than lost"),
                          include.lowest = TRUE)) |>
  filter(!is.na(yn_inter_migr))
  
summary(aussie_data)  

aussie_data
```

```{r}
ggplot(aussie_data, aes(x = total_pop, y = pct_over_migr, color = yn_fert_rate)) +
  geom_point(alpha = 0.6,
             size = 0.75) +
  facet_wrap(~yn_inter_migr) +
  geom_smooth(method = "lm",
              se = FALSE) +
  theme_solarized(light = FALSE) +
  scale_color_solarized() +
  scale_color_solarized(name = "Fertility Rate") +
  labs(x = "Population", y = "New Overseas Migrants as % of Pop.") 
```



https://dataexplorer.abs.gov.au/vis?fs[0]=Data%20by%20region%2C0%7CMain%20Structure%20and%20Greater%20Capital%20City%20Statistical%20Areas%23ASGS%23&pg=0&fc=Data%20by%20region&df[ds]=DATA_BY_REGION_TOPICS&df[id]=ABS_REGIONAL_ASGS2021&df[ag]=ABS&df[vs]=1.3.0&pd=2022%2C2022&dq=CABEE_5%2BCABEE_15%2BCABEE_10%2BMIGRATION_7%2BMIGRATION_4%2BBD_3%2BBD_4%2BBD_2%2BERP_P_20.SA3..A&ly[cl]=MEASURE&ly[rw]=ASGS_2021&to[TIME_PERIOD]=false&isAvailabilityDisabled=false&snb=2 (accessed: April 18th, 2025)
